src/main/java/org/onee/dfc/ifpm/model/Proposition.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.onee.dfc.ifpm.model;

import lombok.*;

import javax.persistence.*;
import java.util.Date;

/**
 *
 * @author youne
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@Builder(toBuilder = true)
@AllArgsConstructor
public class Proposition {

    @Id
    @GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY )
    private Integer id ;
    private Date dateproposition;
    private Integer nbrthemeproposevcanim;
    private Integer autretheme;
    private Integer totalthemeproposesansdoublant ;
    private Integer nbranimateurvcdoublant ;
    private Integer nbranimateurproposesansdoublant ;
    private Integer nbranimateurexistantbda;
    private String cv;
    private String fmi;

    @ManyToOne
    private Direction direction;
    
}

src/main/java/org/onee/dfc/ifpm/controller/PropositionController.java
package org.onee.dfc.ifpm.controller;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.collections4.IteratorUtils;
import org.onee.dfc.ifpm.config.Messages;
import org.onee.dfc.ifpm.model.Proposition;
import org.onee.dfc.ifpm.repository.PropositionRepository;
import org.springframework.stereotype.Controller;
import org.springframework.web.context.annotation.SessionScope;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.onee.dfc.ifpm.controller.util.JsfUtil.PersistAction;
import org.onee.dfc.ifpm.controller.util.JsfUtil;

@Controller("propositionController")
@SessionScope
@Slf4j
@RequiredArgsConstructor
public class PropositionController implements Serializable {

    private final PropositionRepository ejbFacade;
    private final Messages messages;

    private List<Proposition> items = null;
    private Proposition selected;

    public Proposition getSelected() {
        return selected;
    }

    public void setSelected(Proposition selected) {
        this.selected = selected;
    }

    private PropositionRepository getFacade() {
        return ejbFacade;
    }

    public Proposition prepareCreate() {
        selected = new Proposition();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, messages.get("PropositionCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, messages.get("PropositionUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, messages.get("PropositionDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Proposition> getItems() {
        if (items == null) {
            items = IteratorUtils.toList(getFacade().findAll().iterator());
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().save(selected);
                } else {
                    getFacade().delete(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (Exception ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, messages.get("PersistenceErrorOccured"));
                }
            }
//            catch (Exception ex) {
//                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
//                JsfUtil.addErrorMessage(ex, messages.get("PersistenceErrorOccured"));
//            }
        }
    }

    public Proposition getProposition(java.lang.Integer id) {
        return getFacade().findById(id).orElse(null);
    }

    public List<Proposition> getItemsAvailableSelectMany() {
        return IteratorUtils.toList(getFacade().findAll().iterator());
    }

    public List<Proposition> getItemsAvailableSelectOne() {
        return IteratorUtils.toList(getFacade().findAll().iterator());
    }

    @FacesConverter(forClass = Proposition.class)
    public static class PropositionControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PropositionController controller = (PropositionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "propositionController");
            return controller.getProposition(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Proposition) {
                Proposition o = (Proposition) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Proposition.class.getName()});
                return null;
            }
        }

    }

}

src/main/webapp/proposition/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PropositionCreateDlg" widgetVar="PropositionCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreatePropositionTitle}">
            <h:form id="PropositionCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{propositionController.selected != null}">
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_dateproposition}" for="dateproposition" />
                        <p:inputText id="dateproposition" value="#{propositionController.selected.dateproposition}" title="#{bundle.CreatePropositionTitle_dateproposition}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_nbrthemeproposevcanim}" for="nbrthemeproposevcanim" />
                        <p:inputText id="nbrthemeproposevcanim" value="#{propositionController.selected.nbrthemeproposevcanim}" title="#{bundle.CreatePropositionTitle_nbrthemeproposevcanim}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_autretheme}" for="autretheme" />
                        <p:inputText id="autretheme" value="#{propositionController.selected.autretheme}" title="#{bundle.CreatePropositionTitle_autretheme}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_totalthemeproposesansdoublant}" for="totalthemeproposesansdoublant" />
                        <p:inputText id="totalthemeproposesansdoublant" value="#{propositionController.selected.totalthemeproposesansdoublant}" title="#{bundle.CreatePropositionTitle_totalthemeproposesansdoublant}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_nbranimateurvcdoublant}" for="nbranimateurvcdoublant" />
                        <p:inputText id="nbranimateurvcdoublant" value="#{propositionController.selected.nbranimateurvcdoublant}" title="#{bundle.CreatePropositionTitle_nbranimateurvcdoublant}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_nbranimateurproposesansdoublant}" for="nbranimateurproposesansdoublant" />
                        <p:inputText id="nbranimateurproposesansdoublant" value="#{propositionController.selected.nbranimateurproposesansdoublant}" title="#{bundle.CreatePropositionTitle_nbranimateurproposesansdoublant}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_nbranimateurexistantbda}" for="nbranimateurexistantbda" />
                        <p:inputText id="nbranimateurexistantbda" value="#{propositionController.selected.nbranimateurexistantbda}" title="#{bundle.CreatePropositionTitle_nbranimateurexistantbda}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_cv}" for="cv" />
                        <p:inputText id="cv" value="#{propositionController.selected.cv}" title="#{bundle.CreatePropositionTitle_cv}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_fmi}" for="fmi" />
                        <p:inputText id="fmi" value="#{propositionController.selected.fmi}" title="#{bundle.CreatePropositionTitle_fmi}" />
                        <p:outputLabel value="#{bundle.CreatePropositionLabel_direction}" for="direction" />
                        <p:selectOneMenu id="direction" value="#{propositionController.selected.direction}" >
                            <f:selectItems value="#{directionController.itemsAvailableSelectOne}"
                                           var="directionItem"
                                           itemValue="#{directionItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{propositionController.create}" value="#{bundle.Save}" update="display,:PropositionListForm:datalist,:growl" oncomplete="handleSubmit(args,'PropositionCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PropositionCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/proposition/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PropositionEditDlg" widgetVar="PropositionEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditPropositionTitle}">
            <h:form id="PropositionEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{propositionController.selected != null}">
                        <p:outputLabel value="#{bundle.EditPropositionLabel_dateproposition}" for="dateproposition" />
                        <p:inputText id="dateproposition" value="#{propositionController.selected.dateproposition}" title="#{bundle.EditPropositionTitle_dateproposition}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_nbrthemeproposevcanim}" for="nbrthemeproposevcanim" />
                        <p:inputText id="nbrthemeproposevcanim" value="#{propositionController.selected.nbrthemeproposevcanim}" title="#{bundle.EditPropositionTitle_nbrthemeproposevcanim}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_autretheme}" for="autretheme" />
                        <p:inputText id="autretheme" value="#{propositionController.selected.autretheme}" title="#{bundle.EditPropositionTitle_autretheme}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_totalthemeproposesansdoublant}" for="totalthemeproposesansdoublant" />
                        <p:inputText id="totalthemeproposesansdoublant" value="#{propositionController.selected.totalthemeproposesansdoublant}" title="#{bundle.EditPropositionTitle_totalthemeproposesansdoublant}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_nbranimateurvcdoublant}" for="nbranimateurvcdoublant" />
                        <p:inputText id="nbranimateurvcdoublant" value="#{propositionController.selected.nbranimateurvcdoublant}" title="#{bundle.EditPropositionTitle_nbranimateurvcdoublant}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_nbranimateurproposesansdoublant}" for="nbranimateurproposesansdoublant" />
                        <p:inputText id="nbranimateurproposesansdoublant" value="#{propositionController.selected.nbranimateurproposesansdoublant}" title="#{bundle.EditPropositionTitle_nbranimateurproposesansdoublant}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_nbranimateurexistantbda}" for="nbranimateurexistantbda" />
                        <p:inputText id="nbranimateurexistantbda" value="#{propositionController.selected.nbranimateurexistantbda}" title="#{bundle.EditPropositionTitle_nbranimateurexistantbda}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_cv}" for="cv" />
                        <p:inputText id="cv" value="#{propositionController.selected.cv}" title="#{bundle.EditPropositionTitle_cv}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_fmi}" for="fmi" />
                        <p:inputText id="fmi" value="#{propositionController.selected.fmi}" title="#{bundle.EditPropositionTitle_fmi}" />
                        <p:outputLabel value="#{bundle.EditPropositionLabel_direction}" for="direction" />
                        <p:selectOneMenu id="direction" value="#{propositionController.selected.direction}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{directionController.itemsAvailableSelectOne}"
                                           var="directionItem"
                                           itemValue="#{directionItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{propositionController.update}" value="#{bundle.Save}" update="display,:PropositionListForm:datalist,:growl" oncomplete="handleSubmit(args, 'PropositionEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PropositionEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/proposition/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListPropositionTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="PropositionListForm">
                <p:panel header="#{bundle.ListPropositionTitle}">
                    <p:dataTable id="datalist" value="#{propositionController.items}" var="item"
                                 selectionMode="single" selection="#{propositionController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_dateproposition}"/>
                            </f:facet>
                            <h:outputText value="#{item.dateproposition}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_nbrthemeproposevcanim}"/>
                            </f:facet>
                            <h:outputText value="#{item.nbrthemeproposevcanim}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_autretheme}"/>
                            </f:facet>
                            <h:outputText value="#{item.autretheme}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_totalthemeproposesansdoublant}"/>
                            </f:facet>
                            <h:outputText value="#{item.totalthemeproposesansdoublant}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_nbranimateurvcdoublant}"/>
                            </f:facet>
                            <h:outputText value="#{item.nbranimateurvcdoublant}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_nbranimateurproposesansdoublant}"/>
                            </f:facet>
                            <h:outputText value="#{item.nbranimateurproposesansdoublant}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_nbranimateurexistantbda}"/>
                            </f:facet>
                            <h:outputText value="#{item.nbranimateurexistantbda}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_cv}"/>
                            </f:facet>
                            <h:outputText value="#{item.cv}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_fmi}"/>
                            </f:facet>
                            <h:outputText value="#{item.fmi}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPropositionTitle_direction}"/>
                            </f:facet>
                            <h:outputText value="#{item.direction}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{propositionController.prepareCreate}" update=":PropositionCreateForm" oncomplete="PF('PropositionCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":PropositionViewForm" oncomplete="PF('PropositionViewDialog').show()" disabled="#{empty propositionController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":PropositionEditForm" oncomplete="PF('PropositionEditDialog').show()" disabled="#{empty propositionController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{propositionController.destroy}" update=":growl,datalist" disabled="#{empty propositionController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/proposition/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PropositionViewDlg" widgetVar="PropositionViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewPropositionTitle}">
            <h:form id="PropositionViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{propositionController.selected != null}">
                        <h:outputText value="#{bundle.ViewPropositionLabel_dateproposition}"/>
                        <h:outputText value="#{propositionController.selected.dateproposition}" title="#{bundle.ViewPropositionTitle_dateproposition}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_nbrthemeproposevcanim}"/>
                        <h:outputText value="#{propositionController.selected.nbrthemeproposevcanim}" title="#{bundle.ViewPropositionTitle_nbrthemeproposevcanim}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_autretheme}"/>
                        <h:outputText value="#{propositionController.selected.autretheme}" title="#{bundle.ViewPropositionTitle_autretheme}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_totalthemeproposesansdoublant}"/>
                        <h:outputText value="#{propositionController.selected.totalthemeproposesansdoublant}" title="#{bundle.ViewPropositionTitle_totalthemeproposesansdoublant}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_nbranimateurvcdoublant}"/>
                        <h:outputText value="#{propositionController.selected.nbranimateurvcdoublant}" title="#{bundle.ViewPropositionTitle_nbranimateurvcdoublant}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_nbranimateurproposesansdoublant}"/>
                        <h:outputText value="#{propositionController.selected.nbranimateurproposesansdoublant}" title="#{bundle.ViewPropositionTitle_nbranimateurproposesansdoublant}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_nbranimateurexistantbda}"/>
                        <h:outputText value="#{propositionController.selected.nbranimateurexistantbda}" title="#{bundle.ViewPropositionTitle_nbranimateurexistantbda}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_cv}"/>
                        <h:outputText value="#{propositionController.selected.cv}" title="#{bundle.ViewPropositionTitle_cv}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_fmi}"/>
                        <h:outputText value="#{propositionController.selected.fmi}" title="#{bundle.ViewPropositionTitle_fmi}"/>
                        <h:outputText value="#{bundle.ViewPropositionLabel_direction}"/>
                        <h:outputText value="#{propositionController.selected.direction}" title="#{bundle.ViewPropositionTitle_direction}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="PropositionViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>